const ACTIONS = {
    ADD_LOG: "ADD_LOG",
    ADD_TAG: "ADD_TAG",
    ADD_CATEGORY: "ADD_CATEGORY",
    LOGOUT: "LOGOUT",
    SIGNUP: "SIGNUP",
    PROFILE_LOAD: "PROFILE_LOAD",
    FAILED_TO_FETCH_DATA: "FAILED_TO_FETCH_DATA",
    GET_ALL_LOGS: "GET_ALL_LOGS",
    GET_EDIT_LOG_ID: 'GET_EDIT_LOG_ID',
    GET_ALL_CATEGORY: 'GET_ALL_CATEGORY',
    SET_EDIT_LOG_FLAG: 'SET_EDIT_LOG_FLAG',
    UNSET_EDIT_LOG_FLAG: 'UNSET_EDIT_LOG_FLAG',
    SET_EDIT_LOG_ID: 'SET_EDIT_LOG_ID',
    AUTH_START: 'AUTH_START',
    AUTH_USER_LOGIN: "AUTH_USER_LOGIN",
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_INITIATE_LOGOUT: 'AUTH_INITIATE_LOGOUT',
    AUTH_CHECK_TIMEOUT: 'AUTH_CHECK_TIMEOUT',
    AUTH_USER: 'AUTH_USER',
    SET_USER_DATA: 'SET_USER_DATA',
    DELETED_LOG: 'DELETED_LOG',
    COMPLETED_LOG: 'COMPLETED_LOG',
    SET_COOKIE: 'SET_COOKIE'
}

export { ACTIONS };